[project]
name = "autopilot"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "lap>=0.5.13",
    "numpy>=2.5.3",
    "onnx>=1.23.1",
    "onnxruntime-gpu>=1.30.0",
    "onnxslim>=0.1.97",
    "opencv-python>=5.0.0.93",
    "torch>=2.14.0",
    "torchvision>=0.29.0",
    "ultralytics>=8.4.166",
]

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu130" }
torchvision = { index = "pytorch-cu130" }
